export const seedRecords = [
  {
    id: "INC-2026-0142",
    recordType: "Incident",
    title: "Temperature excursion – Incubator IC-12",
    status: "Draft",
    priority: "High",
    sourceChannel: "Slack",
    sourceRef: "https://acme.slack.com/archives/C012LAB/p1758437640000",
    site: "Berlin Lab",
    department: "Microbiology",
    area: "MB-Lab 2",
    occurredAt: "2026-09-21T08:14:00+02:00",
    discoveredAt: "2026-09-21T08:14:00+02:00",
    reportedAt: "2026-09-21T08:14:32+02:00",
    reportedByName: "Lisa Chen",
    reportedByRole: "Lab Technician",
    reportedByEmail: "lisa.chen@lab.example",
    owner: null,
    summary:
      "Incubator IC-12 read 39.2 °C instead of 37.0 °C; two in-process batches affected.",
    description:
      "At 08:14 the incubator IC-12 display showed 39.2 °C against a setpoint of 37.0 °C (±1.0). Batches MB-24091 and MB-24092 were in incubation. Photo of the display and the Slack report are attached.",
    immediateActions:
      "Samples secured. Incubator taken out of service. QA notified via Slack.",
    category: "Equipment",
    subcategory: "Temperature excursion",
    nature: "Unplanned",
    isRepeat: false,
    relatedEventIds: [],
    equipmentName: "Incubator IC-12",
    equipmentId: "EQ-INC-0012",
    methodName: "Microbial enumeration",
    sopId: "SOP-MB-017 v4.2",
    processStep: "Incubation",
    expectedValue: "37.0 ± 1.0",
    actualValue: "39.2",
    unit: "°C",
    limsSampleIds: ["S-88421", "S-88422"],
    batchLots: [
      {
        product: "Product X",
        batchNo: "MB-24091",
        stage: "In testing",
        quantity: null,
        impactUnknown: true,
      },
      {
        product: "Product X",
        batchNo: "MB-24092",
        stage: "In testing",
        quantity: null,
        impactUnknown: true,
      },
    ],
    productNames: ["Product X"],
    reagentLots: [],
    classification: null,
    gxpType: "GMP",
    productImpact: null,
    patientSafetyImpact: null,
    dataIntegrityImpact: null,
    reportabilityImpact: null,
    regulatoryImpact: null,
    impactRationale: null,
    containmentNeeded: null,
    containmentActions: null,
    disposition: null,
    investigationRequired: null,
    investigationOwner: null,
    investigationDueDate: null,
    investigationSummary: null,
    rootCauseMethod: null,
    rootCause: null,
    rootCauseCategory: null,
    contributingFactors: [],
    similarEventsReviewed: null,
    capaRequired: null,
    capaJustification: null,
    capaIds: [],
    effectivenessCheckRequired: null,
    capaActions: [],
    attachments: [
      {
        id: "ATT-001",
        fileName: "slack-message.txt",
        fileType: "text/plain",
        source: "Slack",
        caption: "Original Slack report",
        uploadedAt: "2026-09-21T08:16:10+02:00",
        uploadedBy: "Quality Bot",
        url: "/demo/attachments/slack-message.txt",
      },
      {
        id: "ATT-002",
        fileName: "incubator-display.svg",
        fileType: "image/svg+xml",
        source: "Slack",
        caption: "Display reading 39.2 °C",
        uploadedAt: "2026-09-21T08:16:11+02:00",
        uploadedBy: "Quality Bot",
        url: "/demo/attachments/incubator-display.svg",
      },
      {
        id: "ATT-003",
        fileName: "temp-log.csv",
        fileType: "text/csv",
        source: "Upload",
        caption: "Last 24h temperature log",
        uploadedAt: "2026-09-21T08:16:12+02:00",
        uploadedBy: "Quality Bot",
        url: "/demo/attachments/temp-log.csv",
      },
    ],
    attachmentCount: 3,
    qaReviewer: null,
    qaDecision: null,
    qaComments: null,
    approvedAt: null,
    closedAt: null,
    closureSummary: null,
    electronicSignature: null,
    linkedIncidents: [],
    linkedDeviations: [],
    linkedCapas: [],
    linkedSops: ["SOP-MB-017"],
    linkedEquipment: ["EQ-INC-0012"],
    linkedChangeControls: [],
    draftedFromSlack: true,
    auditTrail: [
      {
        at: "2026-09-21T08:16:00+02:00",
        actor: "Quality Bot",
        action: "Created record",
        from: null,
        to: "Draft",
        comment: "Drafted from Slack message in #lab-incidents",
      },
      {
        at: "2026-09-21T08:16:12+02:00",
        actor: "Quality Bot",
        action: "Attached files",
        from: "0",
        to: "3",
        comment: "Slack message, display photo, temperature log",
      },
    ],
  },
  {
    id: "DEV-2026-0088",
    recordType: "Deviation",
    title: "Missed stability pull – Chamber ST-04",
    status: "Closed",
    priority: "Medium",
    sourceChannel: "LIMS",
    sourceRef: "LIMS-STAB-8821",
    site: "Berlin Lab",
    department: "QC Chemistry",
    area: "Stability suite",
    occurredAt: "2026-08-04T06:00:00+02:00",
    discoveredAt: "2026-08-04T09:40:00+02:00",
    reportedAt: "2026-08-04T09:55:00+02:00",
    reportedByName: "Tom Berger",
    reportedByRole: "Lab Supervisor",
    reportedByEmail: "tom.berger@lab.example",
    owner: "Maria Alvarez",
    summary: "T=3 month stability pull for Product Y was missed by one calendar day.",
    description:
      "Chamber ST-04 pull for Product Y batch CH-23911 was scheduled 03 Aug. Pull occurred 04 Aug after LIMS overdue alert.",
    immediateActions: "Samples pulled, labelled late, QA notified. Chamber access log attached.",
    category: "Sample Handling",
    subcategory: "Missed timepoint",
    nature: "Unplanned",
    isRepeat: false,
    relatedEventIds: [],
    equipmentName: "Stability chamber ST-04",
    equipmentId: "EQ-ST-0004",
    methodName: "Stability protocol STP-Y-03",
    sopId: "SOP-QC-044 v2.1",
    processStep: "Stability pull",
    expectedValue: "T=3 months on 2026-08-03",
    actualValue: "Pulled 2026-08-04",
    unit: null,
    limsSampleIds: ["ST-33901"],
    batchLots: [
      {
        product: "Product Y",
        batchNo: "CH-23911",
        stage: "Released",
        quantity: "12 units",
        impactUnknown: false,
      },
    ],
    productNames: ["Product Y"],
    reagentLots: [],
    classification: "Deviation",
    gxpType: "GMP",
    productImpact: "None",
    patientSafetyImpact: "None",
    dataIntegrityImpact: "None",
    reportabilityImpact: "Amend report",
    regulatoryImpact: "None",
    impactRationale: "One-day delay; samples remained in specified storage conditions.",
    containmentNeeded: false,
    containmentActions: null,
    disposition: "Use as is",
    investigationRequired: true,
    investigationOwner: "Tom Berger",
    investigationDueDate: "2026-08-18",
    investigationSummary: "Calendar reminder not set after protocol amendment.",
    rootCauseMethod: "5 Whys",
    rootCause: "Protocol amendment did not update the LIMS scheduler.",
    rootCauseCategory: "Method",
    contributingFactors: ["No dual check on scheduler"],
    similarEventsReviewed: "No similar events in 12 months.",
    capaRequired: true,
    capaJustification: "Scheduler update is required after protocol changes.",
    capaIds: ["CAPA-2026-0022"],
    effectivenessCheckRequired: true,
    capaActions: [
      {
        id: "CA-0088-01",
        type: "Corrective",
        description: "Update LIMS scheduler on protocol amendment",
        owner: "QC Chemistry",
        dueDate: "2026-08-20",
        status: "Done",
        evidence: "Change ticket CC-441",
      },
    ],
    attachments: [],
    attachmentCount: 0,
    qaReviewer: "Maria Alvarez",
    qaDecision: "Promote to deviation",
    qaComments: "Closed after CAPA verification.",
    approvedAt: "2026-08-22T11:00:00+02:00",
    closedAt: "2026-08-29T16:20:00+02:00",
    closureSummary: "Deviation closed. Scheduler control implemented.",
    electronicSignature: {
      signedBy: "Maria Alvarez",
      meaning: "Approved",
      signedAt: "2026-08-22T11:00:00+02:00",
    },
    linkedIncidents: [],
    linkedDeviations: [],
    linkedCapas: ["CAPA-2026-0022"],
    linkedSops: ["SOP-QC-044"],
    linkedEquipment: ["EQ-ST-0004"],
    linkedChangeControls: ["CC-441"],
    draftedFromSlack: false,
    auditTrail: [
      {
        at: "2026-08-04T09:56:00+02:00",
        actor: "Tom Berger",
        action: "Created record",
        from: null,
        to: "Draft",
        comment: "Opened from LIMS overdue alert",
      },
      {
        at: "2026-08-29T16:20:00+02:00",
        actor: "Maria Alvarez",
        action: "Changed status",
        from: "Approved",
        to: "Closed",
        comment: "CAPA verified",
      },
    ],
  },
  {
    id: "INC-2026-0138",
    recordType: "Incident",
    title: "Balance drift during weigh-in – BAL-03",
    status: "Under QA Review",
    priority: "Medium",
    sourceChannel: "Manual",
    sourceRef: null,
    site: "Berlin Lab",
    department: "QC Chemistry",
    area: "Weigh room",
    occurredAt: "2026-09-12T14:22:00+02:00",
    discoveredAt: "2026-09-12T14:22:00+02:00",
    reportedAt: "2026-09-12T14:40:00+02:00",
    reportedByName: "Lisa Chen",
    reportedByRole: "Lab Technician",
    reportedByEmail: "lisa.chen@lab.example",
    owner: "Maria Alvarez",
    summary: "Analytical balance BAL-03 failed daily check by 0.4 mg.",
    description:
      "Daily check weight 100.000 mg read 100.400 mg. Work stopped. Adjacent balances used after verification.",
    immediateActions: "Balance taken out of use. Facilities ticket opened.",
    category: "Equipment",
    subcategory: "Calibration drift",
    nature: "Unplanned",
    isRepeat: false,
    relatedEventIds: [],
    equipmentName: "Analytical balance BAL-03",
    equipmentId: "EQ-BAL-0003",
    methodName: null,
    sopId: "SOP-QC-011 v6.0",
    processStep: "Weigh-in",
    expectedValue: "100.000 ± 0.100 mg",
    actualValue: "100.400",
    unit: "mg",
    limsSampleIds: [],
    batchLots: [],
    productNames: [],
    reagentLots: [],
    classification: null,
    gxpType: "GMP",
    productImpact: "Unknown",
    patientSafetyImpact: "None",
    dataIntegrityImpact: "Possible",
    reportabilityImpact: null,
    regulatoryImpact: null,
    impactRationale: null,
    containmentNeeded: true,
    containmentActions: "Weighings since last passing check under review.",
    disposition: null,
    investigationRequired: true,
    investigationOwner: "Tom Berger",
    investigationDueDate: "2026-09-26",
    investigationSummary: null,
    rootCauseMethod: null,
    rootCause: null,
    rootCauseCategory: null,
    contributingFactors: [],
    similarEventsReviewed: null,
    capaRequired: null,
    capaJustification: null,
    capaIds: [],
    effectivenessCheckRequired: null,
    capaActions: [],
    attachments: [],
    attachmentCount: 0,
    qaReviewer: "Maria Alvarez",
    qaDecision: null,
    qaComments: null,
    approvedAt: null,
    closedAt: null,
    closureSummary: null,
    electronicSignature: null,
    linkedIncidents: [],
    linkedDeviations: [],
    linkedCapas: [],
    linkedSops: ["SOP-QC-011"],
    linkedEquipment: ["EQ-BAL-0003"],
    linkedChangeControls: [],
    draftedFromSlack: false,
    auditTrail: [
      {
        at: "2026-09-12T14:41:00+02:00",
        actor: "Lisa Chen",
        action: "Created record",
        from: null,
        to: "Draft",
        comment: "Manual intake",
      },
      {
        at: "2026-09-12T16:10:00+02:00",
        actor: "Maria Alvarez",
        action: "Changed status",
        from: "Submitted",
        to: "Under QA Review",
        comment: null,
      },
    ],
  },
  {
    id: "INC-2026-0131",
    recordType: "Incident",
    title: "Sample receipt label mismatch",
    status: "Investigation",
    priority: "Low",
    sourceChannel: "Email",
    sourceRef: "ticket-4412",
    site: "Berlin Lab",
    department: "Sample Receipt",
    area: "Goods-in",
    occurredAt: "2026-09-03T10:05:00+02:00",
    discoveredAt: "2026-09-03T10:18:00+02:00",
    reportedAt: "2026-09-03T10:30:00+02:00",
    reportedByName: "Tom Berger",
    reportedByRole: "Lab Supervisor",
    reportedByEmail: "tom.berger@lab.example",
    owner: "Maria Alvarez",
    summary: "Courier paperwork listed S-88011; vial label showed S-88012.",
    description:
      "Two companion samples arrived together. Paperwork and vial IDs did not match. Samples quarantined.",
    immediateActions: "Quarantine. Courier contacted. Customer notified.",
    category: "Sample Handling",
    subcategory: "Identity",
    nature: "Unplanned",
    isRepeat: false,
    relatedEventIds: [],
    equipmentName: null,
    equipmentId: null,
    methodName: null,
    sopId: "SOP-SR-002 v3.0",
    processStep: "Receipt",
    expectedValue: "Label matches CoA",
    actualValue: "S-88011 vs S-88012",
    unit: null,
    limsSampleIds: ["S-88011", "S-88012"],
    batchLots: [],
    productNames: [],
    reagentLots: [],
    classification: "Incident only",
    gxpType: "ISO 17025",
    productImpact: "Possible",
    patientSafetyImpact: "N/A",
    dataIntegrityImpact: "None",
    reportabilityImpact: "Hold results",
    regulatoryImpact: "None",
    impactRationale: "Identity not confirmed; testing not started.",
    containmentNeeded: true,
    containmentActions: "Both vials quarantined pending customer confirmation.",
    disposition: "Quarantine",
    investigationRequired: true,
    investigationOwner: "Tom Berger",
    investigationDueDate: "2026-09-17",
    investigationSummary: "Awaiting courier scan logs.",
    rootCauseMethod: null,
    rootCause: null,
    rootCauseCategory: null,
    contributingFactors: [],
    similarEventsReviewed: null,
    capaRequired: null,
    capaJustification: null,
    capaIds: [],
    effectivenessCheckRequired: null,
    capaActions: [],
    attachments: [],
    attachmentCount: 0,
    qaReviewer: "Maria Alvarez",
    qaDecision: "Approve as incident",
    qaComments: null,
    approvedAt: null,
    closedAt: null,
    closureSummary: null,
    electronicSignature: null,
    linkedIncidents: [],
    linkedDeviations: [],
    linkedCapas: [],
    linkedSops: ["SOP-SR-002"],
    linkedEquipment: [],
    linkedChangeControls: [],
    draftedFromSlack: false,
    auditTrail: [
      {
        at: "2026-09-03T10:31:00+02:00",
        actor: "Tom Berger",
        action: "Created record",
        from: null,
        to: "Draft",
        comment: "Opened from email",
      },
    ],
  },
];
