variable "name" {
  description = "Name prefix for AWS resources."
  type        = string
  default     = "qms-demo"
}

variable "aws_region" {
  description = "AWS region. eu-central-1 (Frankfurt) is the default."
  type        = string
  default     = "eu-central-1"
}

variable "instance_type" {
  description = "EC2 size. t3.small (2 GB) is the default so Docker can build and run the stack."
  type        = string
  default     = "t3.small"
}

variable "hostname" {
  description = "Public DNS name (Cloudflare-proxied A record). Browser HTTPS is at https://<hostname>."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\\.[a-z]{2,}$", var.hostname))
    error_message = "hostname must be a DNS name with a dot (for example demo.example.com)."
  }
}

variable "cloudflare_zone_id" {
  description = "Cloudflare zone ID that owns hostname. Token comes from CLOUDFLARE_API_TOKEN, not this variable."
  type        = string
}

variable "allow_cidrs" {
  description = "IPv4 CIDRs to whitelist via zone IP Access Rules. Empty creates no rules."
  type        = list(string)
  default     = []

  validation {
    condition     = alltrue([for c in var.allow_cidrs : can(cidrhost(c, 0))])
    error_message = "allow_cidrs must be a list of valid CIDRs (for example 203.0.113.10/32)."
  }
}

variable "allowed_cidr" {
  description = "CIDR allowed to SSH to the instance. Empty = detect the apply-er public IP."
  type        = string
  default     = ""

  validation {
    condition     = var.allowed_cidr == "" || can(cidrhost(var.allowed_cidr, 0))
    error_message = "allowed_cidr must be empty or a valid CIDR (for example 203.0.113.10/32)."
  }
}

variable "ssh_public_key" {
  description = "OpenSSH public key installed on the instance. Generated by scripts/deploy-aws.sh."
  type        = string

  validation {
    condition     = can(regex("^ssh-(ed25519|rsa) ", var.ssh_public_key))
    error_message = "ssh_public_key must be an ssh-ed25519 or ssh-rsa public key."
  }
}

variable "volume_size_gb" {
  description = "Root EBS size. Free tier covers 30 GB of general-purpose storage."
  type        = number
  default     = 8
}
