variable "name" {
  description = "Name prefix for AWS resources."
  type        = string
  default     = "qms-demo"
}

variable "aws_region" {
  description = "AWS region. us-east-1 is the usual free-tier default."
  type        = string
  default     = "us-east-1"
}

variable "instance_type" {
  description = "EC2 size. t3.small (2 GB) is the default so Docker can build and run the stack."
  type        = string
  default     = "t3.small"
}

variable "allowed_cidr" {
  description = "CIDR allowed to reach SSH and HTTP. Empty = detect the apply-er public IP."
  type        = string
  default     = ""

  validation {
    condition     = var.allowed_cidr == "" || can(cidrhost(var.allowed_cidr, 0))
    error_message = "allowed_cidr must be empty or a valid CIDR (for example 203.0.113.10/32)."
  }
}

variable "ssh_public_key" {
  description = "OpenSSH public key installed on the instance. Generated by scripts/deploy-aws.sh."
  type        = string

  validation {
    condition     = can(regex("^ssh-(ed25519|rsa) ", var.ssh_public_key))
    error_message = "ssh_public_key must be an ssh-ed25519 or ssh-rsa public key."
  }
}

variable "volume_size_gb" {
  description = "Root EBS size. Free tier covers 30 GB of general-purpose storage."
  type        = number
  default     = 8
}
