server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 25m;

  location /api/ {
    proxy_pass http://api:4000;
    client_max_body_size 25m;
  }

  location /demo/ {
    proxy_pass http://api:4000;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
